### ISSUE TITLE
디자인 수정 

### ISSUE THREAD

**Issue by wonderino** [jaryogujo-blog/kbo-vis-blog#1]
@leejeonghoon 디자인 간단히 수정 안 필요 (특정 태그에 대한 값 정도만 바꾸는 수준으로 가기)

수정 안 받아서 반영

**Comment by leejeonghoon** [comment]
check

**Comment by leejeonghoon** [comment]
![image](https://cloud.githubusercontent.com/assets/10662388/10266161/7bf0cc6c-6a8b-11e5-841b-896e86dec7d7.png)

![image](https://cloud.githubusercontent.com/assets/10662388/10266162/8269c1ac-6a8b-11e5-92bf-16a89c954f08.png)

모바일에서 접속할 사람은 없겠지만 줄였을 때 'open' 'close'보다 '목차', '닫기'가 더 좋을 것 같음.
![image](https://cloud.githubusercontent.com/assets/10662388/10266166/d420fa1a-6a8b-11e5-9cc6-c965ab1f563b.png)

굳이 컬러까지 넣는다면 열기는
.content .toggle{
color:#385958;}

닫기는 디폴트 혹은 #fff

아까말한것처럼 '열기'만 언더라인이 있어도 좋을듯.

## 삭제

h3~h6밑줄제거
h3, h4, h5, h6
border-bottom properties 삭제

## 추가 혹은 수정

h1{font-size:2.5em;
line-height:1;
border-bottom:#385958 6px solid;}
padding-left:5%;
text-align:left;}

h2{
line-height:1;
border-bottom:#385958 4px solid;
font-size:2em;
text-align:left;}

h3{
font-size:1.4em;
line-height:1;
}

h4{
font-size:1.1em;
line-height:1;
margin: 0 auto 10px;}

h5{
font-size: 1.0em
line-height:1;
margin: 0 auto 9px;}

h6{
font-size: 1.0em
line-height:1;
margin: 0 auto 8px;}

blockquote{
margin-left:5%;
font-size:.8em;
margin-bottom:.9em;
border-left: 4px solid #dddddd;
padding: 0 15px;
margin-top: 0; 
margin-bottom: 2em; 
}

section>p, section>ul, section>ol, section>div{
font-size:.8em;
line-height:1.7em;
margin-bottom:.9em;}

.content a {
border-bottom:#385958 1px solid;}

body{
font-family: "애플 SD 산돌고딕 Neo", "Apple SD Gothic Neo", "Nanum Barun Gothic", "맑은 고딕", "Malgun Gothic", Ngothic, sans-serif;

header{
background-color:#385958}

background-image제거

**Comment by leejeonghoon** [comment]
텍스트는 아까 이야기한 blockquote까지 업데이트 해놨음.

**Comment by leejeonghoon** [comment]
- [ ] 6. 인사이트 . 하이퍼링크 수정
